### ISSUE TITLE
Can not download from Fab / 不能从Fab下载

### ISSUE THREAD

**Issue by aoruLola** [AimoTvT/UniversalInterface#1]
大佬你好，我在Fab中下载[UniversalInterface]插件时报MD-0011-0错误，浏览UE论坛后发现似乎跟UE Market迁移到Fab后的BUG

附上原文地址：
https://forums.unrealengine.com/t/plugin-installation-error-md-0011-0-after-fab-migration/2083033/19

**Comment by AimoTvT** [comment]
是吗，我去看看，我之前都可以下载，也可以github下载到项目，自行编译使用。多谢反馈，这个估计只能等官方修复。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月5日(周四) 凌晨1:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [AimoTvT/UniversalInterface] Can not download from Fab / 不能从Fab下载 (Issue #1)




 
大佬你好，我在Fab中下载[UniversalInterface]插件时报MD-0011-0错误，浏览UE论坛后发现似乎跟UE Market迁移到Fab后的BUG
 
附上原文地址：
 https://forums.unrealengine.com/t/plugin-installation-error-md-0011-0-after-fab-migration/2083033/19

**Comment by AimoTvT** [comment]
已经修复了,非常感谢反馈!
